export const productCategories = [
  { slug: "ceiling-fan", name: "Ceiling Fans" },
  { slug: "coolers", name: "Coolers" },
  { slug: "exhaust-fan", name: "Exhaust Fans" },
  { slug: "electric-iron", name: "Irons" },
  { slug: "madhani", name: "Madhani" },
  { slug: "pedestal-fan", name: "Pedestal Fans" },
  { slug: "heating", name: "Heaters" },
];
interface Product {
  id: number;
  link: string;
  category: string;
  image: string;
  model: string;
  description: string;
  color: string[];
  sweep: string;
  bearing: string;
  winding: string;
  fan: string;
  decoration: string;
  body: string;
  blade: string;
  size: string;
  motor: string;
  capacity: string;
  input: string;
  purpose: string;
  parda: string;
  power: string;
  pump: string;
}

export const products: Product[] = [
  {
    id: 1,
    category: "ceiling-fan",
    image: "/images/ceiling/ceiling1.webp",
    model: "Era",
    description: "",
    color: ["brown", "white", "ivory"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    winding: "Full Copper",
    fan: "High Speed Fan 50W",
    decoration: "Decorative Trims on Blades & Motor",
    link: "/products/ceiling-fan/era",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 2,
    category: "ceiling-fan",
    image: "/images/ceiling/ceiling2.webp",
    model: "Era Plus",
    description: "",
    color: ["brown", "ivory"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    blade: "Heavy Duty",
    winding: "Full Copper",
    decoration: "Decorative Trims on Blades & Motor",
    link: "/products/ceiling-fan/era-plus",
    fan: "",
    body: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 3,
    category: "ceiling-fan",
    image: "/images/ceiling/ceiling3.webp",
    model: "Sportz",

    description: "",
    color: ["brown", "blue", "ivory"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    winding: "Full Copper",
    decoration: "Decorative Trims on Blades & Motor, Unique Paint Combination, Easy Clean & Dust Free",
    body: "All Aluminium Die Cast",
    blade: "Precisely balanced Aluminium Blades",
    link: "/products/ceiling-fan/sportz",
    fan: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 4,
    category: "ceiling-fan",
    image: "/images/ceiling/ceiling4.webp",
    model: "Asta",

    description: "",
    color: ["brown", "ivory"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    winding: "Full Copper",
    body: "All Aluminium Die Cast",
    blade: "Precisely balanced Aluminium Blades",
    decoration: "Decorative Trims on Blades & Motor",
    link: "/products/ceiling-fan/asta",
    fan: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 5,
    category: "ceiling-fan",
    image: "/images/ceiling/ceiling5.webp",
    model: "Sportz Plus",

    description: "",
    color: ["brown", "beige", "ivory", "blue"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    link: "/products/ceiling-fan/sportz-plus",
    winding: "Full Copper",
    fan: "",
    decoration: "Decorative Trims on Blades & Motor",
    body: "All Aluminium Die Cast",
    blade: "Precisely balanced Aluminium Blades",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },

  {
    id: 6,
    category: "ceiling-fan",
    image: "/images/ceiling/ceiling7.webp",
    model: "Magna",

    description: "",
    color: ["pearl-ivory", "golden-brown", "silver-blue"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    link: "/products/ceiling-fan/magna",
    winding: "Full Copper",
    fan: "",
    decoration: "Decorative Trims on Blades & Motor",
    body: "All Aluminium Die Cast",
    blade: "Precisely balanced Aluminium Blades",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "Low Consumption",
    pump: ""
  },
  {
    id: 7,
    category: "cooler",
    image: "/images/cooler/cooler1.webp",
    model: "ZX-01",
    color: ["powder-coating"],
    description:
      "",
    size: "25 * 25 * 36",
    motor: "Exhaust 1.5''",
    capacity: "90 Ltr",
    link: "/products/cooler/zx-01",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*4 Metal",
    input: "",
    purpose: "",
    parda: "Grass / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 8,
    category: "cooler",
    image: "/images/cooler/cooler2.webp",
    model: "Duct",
    color: ["powder-coating"],

    description:
      "",
    size: "24 * 24 * 60",
    motor: "GC Cooper Motor",
    capacity: "100 Ltr",
    link: "/products/cooler/duct",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*4 Metal",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / Plastic",
    power: "",
    pump: "36W",
  },
  {
    id: 9,
    category: "cooler",
    image: "/images/cooler/cooler3.webp",
    model: "Baby",
    color: ["powder-coating"],

    description:
      "",
    size: "17 * 17 * 24",
    motor: "High Speed Kit",
    capacity: "30 Ltr",
    link: "/products/cooler/baby",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "9*3 Plastic",
    input: "",
    purpose: "",
    parda: "Ghas / G.I. Parda",
    power: "",
    pump: "9W",
  },
  {
    id: 10,
    category: "cooler",
    image: "/images/cooler/cooler4.webp",
    model: "ZX-02",
    color: ["powder-coating"],

    description:
      "",
    size: "25 * 25 * 48",
    motor: "Exhaust 1.5''",
    capacity: "100 Ltr",
    link: "/products/cooler/zx-02",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*4 Metal",
    input: "",
    purpose: "",
    parda: "Grass / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 11,
    category: "cooler",
    image: "/images/cooler/cooler5.webp",
    model: "CG-04",
    color: ["powder-coating"],

    description:
      "",
    size: "26 * 18 * 50",
    motor: "110 Dai Motor 32mm",
    capacity: "80 Ltr",
    link: "/products/cooler/cg-04",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 12,
    category: "cooler",
    image: "/images/cooler/cooler6.webp",
    model: "CG-03",
    color: ["powder-coating"],

    description:
      "",
    size: "27 * 18 * 55",
    motor: "110 Dai Motor 32mm",
    capacity: "90 Ltr",
    link: "/products/cooler/cg-03",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 13,
    category: "cooler",
    image: "/images/cooler/cooler7.webp",
    model: "CG-02",
    color: ["powder-coating"],

    description:
      "",
    size: "27 * 18 * 50",
    motor: "110 Dai Motor 32mm",
    capacity: "90 Ltr",
    link: "/products/cooler/cg-02",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 14,
    category: "cooler",
    image: "/images/cooler/cooler8.webp",
    model: "CG-01",
    color: ["powder-coating"],

    description:
      "",
    size: "24 * 16 * 42",
    motor: "110 Dai Motor 28mm",
    capacity: "60 Ltr",
    link: "/products/cooler/cg-01",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "16*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 15,
    category: "cooler",
    image: "/images/cooler/cooler9.webp",
    model: "Commercial",
    color: [],

    description:
      "",
    size: "32 * 24 * 50",
    motor: "110 Dai Motor 36mm",
    capacity: "90 Ltr",
    link: "/products/cooler/commercial",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*4 Aluminium",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "36W",
  },
  {
    id: 16,
    category: "cooler",
    image: "/images/cooler/cooler10.webp",
    model: "Sumo",

    description:
      "",
    size: "29 * 22 * 48",
    motor: "110 Dai Motor 32mm",
    capacity: "125 Ltr",
    link: "/products/cooler/sumo",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 17,
    category: "cooler",
    image: "/images/cooler/cooler11.webp",
    model: "Skycool Tower 20''",

    description:
      "",
    size: "24 * 18 * 54",
    motor: "110 Dai Motor 32mm",
    capacity: "110 Ltr",
    link: "/products/cooler/skycool-tower-20",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 18,
    category: "exhaust-fan",
    image: "/images/exhaust/exhaust1.jpg",
    model: "Exhaust Fan",

    description:
      "",

    link: "/products/exhaust-fan/exhaust-fan",
    color: [],
    sweep: "",
    bearing: "Double Ball Bearing",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "450mm / 375mm / 225mm",
    motor: "Soundless Motor",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 19,
    category: "exhaust-fan",
    image: "/images/exhaust/exhaust2.jpg",
    model: "Fresh Air Fan",

    description: "",

    link: "/products/exhaust-fan/fresh-air-fan",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "450mm / 375mm / 300mm / 225mm",
    motor: "Highspeed Motor",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 20,
    category: "electric-iron",
    image: "/images/iron/iron1.webp",
    model: "Magic",

    description: "",

    link: "/products/electric-iron/magic",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 21,
    category: "electric-iron",
    image: "/images/iron/iron2.webp",
    model: "Plancha",

    description: "",

    link: "/products/electric-iron/plancha",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 22,
    category: "pedestal-fan",
    image: "/images/pedestal/pedestal1.jpg",
    model: "Pedestal-18",

    description:
      "",

    link: "/products/pedestal-fan/pedestal-18",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "Heavy Duty & Sturdy Motor",
    capacity: "",
    input: "",
    purpose: "Both Commercial & Domestic",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 23,
    category: "pedestal-fan",
    image: "/images/pedestal/pedestal2.jpg",
    model: "Pedestal-16",

    description:
      "",

    link: "/products/pedestal-fan/pedestal-16",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "Heavy Duty & Sturdy Motor",
    capacity: "",
    input: "",
    purpose: "Both Commercial & Domestic",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 24,
    category: "heating",
    image: "/images/heating/heater1.jpg",
    model: "Quartz Heater",

    description: "",

    link: "/products/heating/quartz-heater",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "400W / 800W",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 25,
    category: "heating",
    image: "/images/heating/heater2.jpg",
    model: "Heater BT Model",

    description: "",
    link: "/products/heating/heater-bt-model",
    color: ["grey", "red", "blue"],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "1000W / 2000W",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 26,
    category: "heating",
    image: "/images/heating/immersion1.webp",
    model: "Immersion Rod",

    description: "",
    link: "/products/heating/immersion-rod",
    input: "1000W / 1500W / 2000W",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 27,
    category: "madhani",
    image: "/images/madhani/madhani1.webp",
    model: "Madhani",

    description:
      "",
    link: "/products/madhani/madhani",
    purpose: "Both Commercial & Domestic",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "Heavy Duty & Sturdy Motor",
    capacity: "",
    input: "",
    parda: "",
    power: "",
    pump: "",
  },
];
