export const productCategories = [
  { slug: "ceiling-fans", name: "Ceiling Fans", banner: "/images/banners/ceiling-fans.webp", description: "Add a dash of elegance amalgamated with power, performance, comfort, safety and durability. The Virgo ceiling fans are an imperative part of every home and are built to be energy efficient. Add a sense of style and exuberance to your rooms and offices with our innovative and trendy designs. With easy installation, our range of ceiling fans is a fit and forget proposition. Ceiling fans are an imperative part of any household. What you select for your house depicts your style and when people walk in through that door, Virgo ceiling fans help you make an impression. Available for the best price online, the latest fans for your roof come in different varieties. Embrace your choices with options like premium underlight fans, energy saving fans, decorative fans, metallic fans, high speed fans, regular fans etc. It is only with these appliances, that a house feels like home and we understand this. The biggest benefit with Virgo fans is that there is no compromise on the performance and the energy usage is always minimum. It is time you upgrade your homes with the most trendy and unique designer fans. Explore the range of fans online relaxing on the couch and make a statement" },
  { slug: "coolers", name: "Coolers", banner: "/images/banners/coolers.webp", description: "Being a pioneer in product innovation, Virgo has once again brought in a unique range of smart coolers with Breatheezee Technology TM. Unlike the traditional coolers that work on natural evaporative cooling theory, Virgo air coolers - with Breatheezee Technology TM - feature dust filters on three sides and completely collapsible louvers on the front to prevent dust from entering the cooler. The specially processed anti-bacterial, anti-erosion and anti-deformation honeycomb pads have good hydrophilic properties to absorb remaining dust particles and cleanse air thoroughly. Virgo air coolers have distinctive features like covered water tank to prevent mosquito breeding, auto drain for easy drainage of water, humidity regulator to regulate water flow on pads, temperature display and much more. Their compact design and air purification system further add to their finesse, making these air coolers a priced possession during summers. All in all, loaded with excellent features, Virgo air coolers are unbeatable when it comes to best-in-class features, safety, portability and convenience. Experience cleaner, healthier and breathable air with the range of Virgo air coolers!" },
  { slug: "exhaust-fans", name: "Exhaust Fans", banner: "/images/banners/exhaust-fans.webp", description: "A vital way of maintaining good health is appropriate air circulation. Good ventilation keeps bad odors, impurities and other unsafe gases away, and stops the formation of harmful mold inside your home. A proper ventilation device keeps your home away from unfortunate damage. Exhaust fans are a means to make sure the appropriate ventilation in your home. The major areas where it should be installed are the restroom as well as the kitchen as they usually contain most of the moisture and odors. Who likes to sit in room full of odors? You guessed it right, nobody. Presenting to you with the ideal solution to all your odors problems, The Virgo range of domestic exhaust fans removes stale odors, leaving your rooms fresh and healthy. Their noiseless operation along with aesthetic looks, high utility and performance make these multipurpose machines a must have. With a sleek and trendy design, Virgo exhaust fans are lightweight and carry out their functions silently. These fans also last for a longer period as they have a rust proof body and blades. Though, it is essential that these fans are taken good care of so that they last and function for long. Provided that these fans perform an important function, it is required that every home has at least one installed in their kitchen as well as bathroom. You can simply search for the different fans price and reviews, and then proceed to purchase the best one online. Choose also from different shapes, sizes, colors and more."  },
  { slug: "electric-irons", name: "Irons", banner: "/images/banners/electric-irons.webp", description: "Start your day crease-free with Virgo' collection of dry iron range. Whether it is a gentle fabric like silk or heavily-embroidered thick curtain, get a perfect result each time. Large water tank and triple-layered Teflon coating ensure continuous steamy performance and silky-smooth glide over your clothes without damaging them."  },
  { slug: "madhani", name: "Madhani", banner: "/images/banners/madhani.webp", description: "Introducing Virgo Madhani, a cherished traditional kitchen tool steeped in the rich culinary heritage of India. Also known as the 'Madhani or Butter Churner,' this timeless device has been a staple in Indian households for generations. Crafted from sturdy materials like wood or metal, the Madhani features a cylindrical design with a central rod adorned with multiple discs or paddles. Its operation is simple yet effective: by manually rotating the Madhani, the paddles agitate the contents, facilitating the separation of cream from milk and the churning of butter. Beyond its practical utility, the Madhani symbolizes the enduring connection to tradition and the art of home cooking. Explore our collection and bring a touch of authentic Indian culinary culture into your kitchen with the iconic Madhani."  },
  { slug: "pedestal-fans", name: "Pedestal Fans", banner: "/images/banners/pedestal-fans.webp", description: "Pedestal fans are a good substitute to ceiling fans and are perfect to be used in homes where space can be a problem. Besides keeping a room cool, these fans are also quite suitable for monsoon or chilly winters when you have a load of wet clothes that you wish to dry. And moreover, opposite of ceiling fans, these fans can be installed to blow air in a specific direction, which is very much convenient. The majority of these fans come with multiple speed settings, letting you set as well as adjust them according to your requirements. The high-quality fans come with the silent operation feature; therefore you don't have to be concerned about being disturbed by a continuous buzzing noise when you use them. Features like jerk free oscillation and 2000 RPM hi air thrust make Virgo pedestal fans worth every penny. Virgo range of pedestal fans come with unique features and conveniences like remote controls and timer settings to control on/off functions, these fans are ideal for use in homes, clubs, restaurants and lobbies. Sturdy mount bases, adjustable height and powerful air flow make them even better and easy to use. Pedestal fans with castor wheels provide an added advantage of easy mobility. To find the best pedestal fan India, you can go online. Explore the prices and reviews of your preferred model to make a smart buy, today!"  },
  { slug: "heating", name: "Heaters", banner: "/images/banners/heating.webp", description: "Stay warm and cozy this winter with Virgo' comprehensive range of heating solutions. Get uniform distribution of heat in every corner of your home. Our electric heaters for homes are safe to use, consume less electricity, and retain heat long after you turn them off. Introducing Virgo Immersion Water Heater with automatic cut-off, which saves more energy and electricity bill. The nickel plating avoid corrosion and makes it long lasting. The water resistant material protects from any kind of electric shock and the protection cover avoids the unexpected touch to the water heater."  },
];
interface Product {
  id: number;
  link: string;
  category: string;
  image: string;
  model: string;
  description: string;
  color: string[];
  sweep: string;
  bearing: string;
  winding: string;
  fan: string;
  decoration: string;
  body: string;
  blade: string;
  size: string;
  motor: string;
  capacity: string;
  input: string;
  purpose: string;
  parda: string;
  power: string;
  pump: string;
}

export const products: Product[] = [
  {
    id: 1,
    category: "ceiling-fans",
    image: "/images/ceiling-fans/ceiling1.webp",
    model: "Era",
    description: "",
    color: ["brown", "white", "ivory"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    winding: "Full Copper",
    fan: "High Speed Fan 50W",
    decoration: "Decorative Trims on Blades & Motor",
    link: "/products/ceiling-fans/era",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 2,
    category: "ceiling-fans",
    image: "/images/ceiling-fans/ceiling2.webp",
    model: "Era Plus",
    description: "",
    color: ["brown", "ivory"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    blade: "Heavy Duty",
    winding: "Full Copper",
    decoration: "Decorative Trims on Blades & Motor",
    link: "/products/ceiling-fans/era-plus",
    fan: "",
    body: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 3,
    category: "ceiling-fans",
    image: "/images/ceiling-fans/ceiling3.webp",
    model: "Sportz",

    description: "",
    color: ["brown", "blue", "ivory"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    winding: "Full Copper",
    decoration: "Decorative Trims on Blades & Motor, Unique Paint Combination, Easy Clean & Dust Free",
    body: "All Aluminium Die Cast",
    blade: "Precisely balanced Aluminium Blades",
    link: "/products/ceiling-fans/sportz",
    fan: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 4,
    category: "ceiling-fans",
    image: "/images/ceiling-fans/ceiling4.webp",
    model: "Asta",

    description: "",
    color: ["brown", "ivory"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    winding: "Full Copper",
    body: "All Aluminium Die Cast",
    blade: "Precisely balanced Aluminium Blades",
    decoration: "Decorative Trims on Blades & Motor",
    link: "/products/ceiling-fans/asta",
    fan: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 5,
    category: "ceiling-fans",
    image: "/images/ceiling-fans/ceiling5.webp",
    model: "Sportz Plus",

    description: "",
    color: ["brown", "beige", "ivory", "blue"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    link: "/products/ceiling-fans/sportz-plus",
    winding: "Full Copper",
    fan: "",
    decoration: "Decorative Trims on Blades & Motor",
    body: "All Aluminium Die Cast",
    blade: "Precisely balanced Aluminium Blades",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },

  {
    id: 6,
    category: "ceiling-fans",
    image: "/images/ceiling-fans/ceiling7.webp",
    model: "Magna",

    description: "",
    color: ["pearl-ivory", "golden-brown", "silver-blue"],
    sweep: "1200mm",
    bearing: "Double Ball Bearing",
    link: "/products/ceiling-fans/magna",
    winding: "Full Copper",
    fan: "",
    decoration: "Decorative Trims on Blades & Motor",
    body: "All Aluminium Die Cast",
    blade: "Precisely balanced Aluminium Blades",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "Low Consumption",
    pump: ""
  },
  {
    id: 7,
    category: "coolers",

    image: "/images/coolers/cooler1.webp",
    model: "ZX-01",
    color: ["powder-coating"],
    description:
      "",
    size: "25 * 25 * 36",
    motor: "Exhaust 1.5''",
    capacity: "90 Ltr",
    link: "/products/coolers/zx-01",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*4 Metal",
    input: "",
    purpose: "",
    parda: "Grass / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 8,
    category: "coolers",

    image: "/images/coolers/cooler2.webp",
    model: "Duct",
    color: ["powder-coating"],

    description:
      "",
    size: "24 * 24 * 60",
    motor: "GC Cooper Motor",
    capacity: "100 Ltr",
    link: "/products/coolers/duct",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*4 Metal",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / Plastic",
    power: "",
    pump: "36W",
  },
  {
    id: 9,
    category: "coolers",

    image: "/images/coolers/cooler3.webp",
    model: "Baby",
    color: ["powder-coating"],

    description:
      "",
    size: "17 * 17 * 24",
    motor: "High Speed Kit",
    capacity: "30 Ltr",
    link: "/products/coolers/baby",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "9*3 Plastic",
    input: "",
    purpose: "",
    parda: "Ghas / G.I. Parda",
    power: "",
    pump: "9W",
  },
  {
    id: 10,
    category: "coolers",

    image: "/images/coolers/cooler4.webp",
    model: "ZX-02",
    color: ["powder-coating"],

    description:
      "",
    size: "25 * 25 * 48",
    motor: "Exhaust 1.5''",
    capacity: "100 Ltr",
    link: "/products/coolers/zx-02",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*4 Metal",
    input: "",
    purpose: "",
    parda: "Grass / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 11,
    category: "coolers",

    image: "/images/coolers/cooler5.webp",
    model: "CG-04",
    color: ["powder-coating"],

    description:
      "",
    size: "26 * 18 * 50",
    motor: "110 Dai Motor 32mm",
    capacity: "80 Ltr",
    link: "/products/coolers/cg-04",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 12,
    category: "coolers",

    image: "/images/coolers/cooler6.webp",
    model: "CG-03",
    color: ["powder-coating"],

    description:
      "",
    size: "27 * 18 * 55",
    motor: "110 Dai Motor 32mm",
    capacity: "90 Ltr",
    link: "/products/coolers/cg-03",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 13,
    category: "coolers",

    image: "/images/coolers/cooler7.webp",
    model: "CG-02",
    color: ["powder-coating"],

    description:
      "",
    size: "27 * 18 * 50",
    motor: "110 Dai Motor 32mm",
    capacity: "90 Ltr",
    link: "/products/coolers/cg-02",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 14,
    category: "coolers",

    image: "/images/coolers/cooler8.webp",
    model: "CG-01",
    color: ["powder-coating"],

    description:
      "",
    size: "24 * 16 * 42",
    motor: "110 Dai Motor 28mm",
    capacity: "60 Ltr",
    link: "/products/coolers/cg-01",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "16*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 15,
    category: "coolers",

    image: "/images/coolers/cooler9.webp",
    model: "Commercial",
    color: [],

    description:
      "",
    size: "32 * 24 * 50",
    motor: "110 Dai Motor 36mm",
    capacity: "90 Ltr",
    link: "/products/coolers/commercial",
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*4 Aluminium",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "36W",
  },
  {
    id: 16,
    category: "coolers",

    image: "/images/coolers/cooler10.webp",
    model: "Sumo",

    description:
      "",
    size: "29 * 22 * 48",
    motor: "110 Dai Motor 32mm",
    capacity: "125 Ltr",
    link: "/products/coolers/sumo",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 17,
    category: "coolers",

    image: "/images/coolers/cooler11.webp",
    model: "Skycool Tower 20''",

    description:
      "",
    size: "24 * 18 * 54",
    motor: "110 Dai Motor 32mm",
    capacity: "110 Ltr",
    link: "/products/coolers/skycool-tower-20",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "Heavy Galvanized Steel",
    blade: "18*6 Plastic",
    input: "",
    purpose: "",
    parda: "Honeycomb Pad / G.I. Parda",
    power: "",
    pump: "18W",
  },
  {
    id: 18,
    category: "exhaust-fans",
    image: "/images/exhaust-fans/exhaust1.jpg",
    model: "Exhaust Fan",

    description:
      "",

    link: "/products/exhaust-fans/exhaust-fan",
    color: [],
    sweep: "",
    bearing: "Double Ball Bearing",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "450mm / 375mm / 225mm",
    motor: "Soundless Motor",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 19,
    category: "exhaust-fans",
    image: "/images/exhaust-fans/exhaust2.jpg",
    model: "Fresh Air Fan",

    description: "",

    link: "/products/exhaust-fans/fresh-air-fan",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "450mm / 375mm / 300mm / 225mm",
    motor: "Highspeed Motor",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 20,
    category: "electric-irons",
    image: "/images/electric-irons/iron1.webp",
    model: "Magic",

    description: "",

    link: "/products/electric-irons/magic",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 21,
    category: "electric-irons",
    image: "/images/electric-irons/iron2.webp",
    model: "Plancha",

    description: "",

    link: "/products/electric-irons/plancha",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 22,
    category: "pedestal-fans",
    image: "/images/pedestal-fans/pedestal1.jpg",
    model: "Pedestal-18",

    description:
      "",

    link: "/products/pedestal-fans/pedestal-18",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "Heavy Duty & Sturdy Motor",
    capacity: "",
    input: "",
    purpose: "Both Commercial & Domestic",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 23,
    category: "pedestal-fans",
    image: "/images/pedestal-fans/pedestal2.jpg",
    model: "Pedestal-16",

    description:
      "",

    link: "/products/pedestal-fans/pedestal-16",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "Heavy Duty & Sturdy Motor",
    capacity: "",
    input: "",
    purpose: "Both Commercial & Domestic",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 24,
    category: "heating",
    image: "/images/heating/heater1.jpg",
    model: "Quartz Heater",

    description: "",

    link: "/products/heating/quartz-heater",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "400W / 800W",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 25,
    category: "heating",
    image: "/images/heating/heater2.jpg",
    model: "Heater BT Model",

    description: "",
    link: "/products/heating/heater-bt-model",
    color: ["grey", "red", "blue"],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    input: "1000W / 2000W",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 26,
    category: "heating",
    image: "/images/heating/immersion1.webp",
    model: "Immersion Rod",

    description: "",
    link: "/products/heating/immersion-rod",
    input: "1000W / 1500W / 2000W",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "",
    capacity: "",
    purpose: "",
    parda: "",
    power: "",
    pump: "",
  },
  {
    id: 27,
    category: "madhani",
    image: "/images/madhani/madhani1.webp",
    model: "Madhani",

    description:
      "",
    link: "/products/madhani/madhani",
    purpose: "Both Commercial & Domestic",
    color: [],
    sweep: "",
    bearing: "",
    winding: "",
    fan: "",
    decoration: "",
    body: "",
    blade: "",
    size: "",
    motor: "Heavy Duty & Sturdy Motor",
    capacity: "",
    input: "",
    parda: "",
    power: "",
    pump: "",
  },
];
